### ISSUE TITLE
Detect whether the GitHub token is read-only and fallback to logging command if needed

### ISSUE THREAD

**Issue by leodido** [listendev/lstn#179]
### Describe the feature or problem you’d like to solve

The (future) `gh-pull-review` reporter will need a GitHub token with write permissions of the GitHub [Review API](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target).

This is because it needs to be able to write stuff into the pull request.

### Proposed solution

If the GitHub token is read-only we could fallback to report via the [logging command](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands) and create annotations similar to the `gh-pull-check` reporter.

### Additional context

NONE

**Comment by fntlnz** [comment]
This is also needed for when the lstn action is installed in a github repo and a PR is opened from a fork.

**Comment by leodido** [comment]
This was done long ago
