### ISSUE TITLE
github comment reporter should not try to comment when github_event != pull_request

### ISSUE THREAD

**Issue by fntlnz** [listendev/lstn#205]
### Describe the bug

Please include:

- v0.5.0
- tested on ubuntu-latest github action

### Steps to reproduce the behavior

1. install the lstn action on a repo
2. open a pr  (not from a fork) and watch lstn working
3. now go to the main branch and watch lstn failing because it tries to comment but the pr number is `0`

### Expected vs actual behavior

actual:
- it tries to comment when running in the main branch

expected:
- it does not try to comment when outside of a PR

### Logs
![image](https://user-images.githubusercontent.com/3083633/228981506-aaf78c6d-8438-4d05-a2d2-67f0fbea22db.png)

**Comment by leodido** [comment]
Yup, on it
